# Generated by Django 2.2.5 on 2019-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
