# Generated by Django 2.2.5 on 2019-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
