# Generated by Django 2.2.5 on 2019-11-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptransaction',
            name='ewo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ewo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouptransaction',
            name='gname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='split.Group'),
        ),
        migrations.AlterField(
            model_name='grouptransaction',
            name='owe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owe', to=settings.AUTH_USER_MODEL),
        ),
    ]
