# Generated by Django 2.2.6 on 2019-11-02 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('txn', '0004_transaction_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=40)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ewo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ewo', to=settings.AUTH_USER_MODEL)),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='txn.Group')),
                ('owe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
