# Generated by Django 2.2.5 on 2019-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0006_auto_20191122_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptransaction',
            name='ewo',
        ),
        migrations.RemoveField(
            model_name='grouptransaction',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='grouptransaction',
            name='owe',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Health and Fitness', 'Health and Fitness'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Rent', 'Rent'), ('Gifts', 'Gifts'), ('Other', 'Other')], max_length=18),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupTransaction',
        ),
    ]
