# Generated by Django 2.2.6 on 2019-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0006_remove_groupa_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Groupa',
        ),
    ]
