# Generated by Django 2.2.6 on 2019-11-01 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('txn', '0008_group_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('gname', models.CharField(max_length=40)),
                ('gets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gets', to=settings.AUTH_USER_MODEL)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
