# Generated by Django 2.2.6 on 2019-11-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('txn', '0010_auto_20191101_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptransaction',
            name='gets',
        ),
        migrations.RemoveField(
            model_name='grouptransaction',
            name='giver',
        ),
    ]
