# Generated by Django 2.2.6 on 2019-11-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('txn', '0011_auto_20191101_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptransaction',
            name='ewo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ewo', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouptransaction',
            name='owe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='owe', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
